### ISSUE TITLE
Put in path for homebrew.

### ISSUE THREAD

**Issue by allanhortle** [puffnfresh/toggle-osx-shadows#18]
Having to type `/usr/local/Cellar/toggle-osx-shadows/osx/bin/toggle-osx-shadows` is pretty annonying

**Comment by bryanbecker** [comment]
Put it in a startup script as a more convenient work-aronud

**Comment by nicolaiskogheim** [comment]
Just `toggle-osx-shadows` works for me. Would have been nice if it autocompleted, though.
But I second @bryanbecker. If you are to always have shadows turned of, you might as well put it in a startup script and never think about shadows again.

**Comment by allanhortle** [comment]
Yeah that works. Stupid me for not trying that in the first place.
